/home/z5102138/anaconda3/envs/py36/bin/python
/home/z5102138/anaconda3/envs/py36/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
/home/z5102138/anaconda3/envs/py36/lib/python3.6/site-packages/torch/cuda/__init__.py:104: UserWarning: 
A100-PCIE-40GB with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the A100-PCIE-40GB GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
/srv/scratch/z5102138/cifar10/all_train_data.pkl
./test_yeast5/model_MLP_both_2000/record_1/MLP_both_2000_1
----------------------



./test_yeast5/model_MLP_both_20000/record_1/MLP_both_20000_1
./test_yeast5/model_MLP_both_15000/record_1/MLP_both_15000_1
./test_yeast5/model_MLP_both_10000/record_1/MLP_both_10000_1
./test_yeast5/model_MLP_both_8000/record_1/MLP_both_8000_1
./test_yeast5/model_MLP_both_5000/record_1/MLP_both_5000_1
./test_yeast5/model_MLP_both_2000/record_1/MLP_both_2000_1
Traceback (most recent call last):
  File "./classifier_MLP/train_MLP.py", line 537, in <module>
    loss.backward()
  File "/home/z5102138/anaconda3/envs/py36/lib/python3.6/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/z5102138/anaconda3/envs/py36/lib/python3.6/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution
/home/z5102138/anaconda3/envs/py36/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
/home/z5102138/anaconda3/envs/py36/lib/python3.6/site-packages/torch/cuda/__init__.py:104: UserWarning: 
A100-PCIE-40GB with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the A100-PCIE-40GB GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
/srv/scratch/z5102138/cifar10/all_train_data.pkl
./test_yeast5/model_MLP_both_2000/record_1/MLP_both_2000_2
----------------------



./test_yeast5/model_MLP_both_20000/record_1/MLP_both_20000_2
./test_yeast5/model_MLP_both_15000/record_1/MLP_both_15000_2
./test_yeast5/model_MLP_both_10000/record_1/MLP_both_10000_2
./test_yeast5/model_MLP_both_8000/record_1/MLP_both_8000_2
./test_yeast5/model_MLP_both_5000/record_1/MLP_both_5000_2
./test_yeast5/model_MLP_both_2000/record_1/MLP_both_2000_2
Traceback (most recent call last):
  File "./classifier_MLP/train_MLP.py", line 537, in <module>
    loss.backward()
  File "/home/z5102138/anaconda3/envs/py36/lib/python3.6/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/z5102138/anaconda3/envs/py36/lib/python3.6/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution
